[tool.poetry]
name = "ansible-personal-playbooks"
version = "0.1.0"
description = ""
authors = ["Robert Smieja"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
ansible = "^2.9.6"

[tool.poetry.dev-dependencies]
ansible-lint = "^4.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
