---
- hosts: localhost
  become: true
- name: Setup Kubeadm and Pre-requisites
  import_playbook: kubeadm/ubuntu.yml
- name: Use Kubeadm to configure a single-node cluster
  import_playbook: single_node_cluster/all.yml
# - name: Setup useful Kubernetes admin utilities like Helm
#   import_playbook: utilities/all.yml
- name: Apply the Calico CNI plugin 
  import_playbook: calico/all.yml
# - name: Apply the OpenEBS Storage plugin
#   import_playbook: openebs/all.yml
# - name: Apply the MetalLB LoadBalancer plugin
#   import_playbook: metallb/all.yml
