---
- hosts: localhost
  pre_tasks:
    - name: Ensure curl is installed
      become: true
      package: 
        name: curl
        state: latest
  tasks:
    - name: Install Python 2 system packages
      become: true
      package: 
        name: "{{ item }}"
        state: latest
      loop:
          - python
          - python-pip
          - python-virtualenv 
    - name: Install Python 2 Pip packages
      pip: 
        executable: pip
        extra_args: --user
        name: "{{ item }}"
        state: latest
      loop:
        - virtualenvwrapper
    - name: Install Python 3 system packages
      become: true
      package: 
        name: "{{ item }}"
        state: latest
      loop:
          - python3
          - python3-pip
          - python3-virtualenv
    - name: Install Python 3 Pip packages
      pip: 
        executable: pip3
        extra_args: --user
        name: "{{ item }}"
        state: latest
      loop:
        - virtualenvwrapper
    - name: Add VirtualEnvWrapper Python to .bash_profile
      lineinfile:
        create: true
        line: export VIRTUALENVWRAPPER_PYTHON="/usr/bin/python3"
        path: "{{ lookup('env','HOME') }}/.bash_profile"
        state: present
    - name: Add VirtualEnvWrapper to .bash_profile
      lineinfile:
        create: true
        line: "source $HOME/.local/bin/virtualenvwrapper.sh"
        path: "{{ lookup('env','HOME') }}/.bash_profile"
        state: present
    - name: Poetry
      block:
      - name: Install Poetry
        shell: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3 - -y
        args:
          creates: "{{ lookup('env','HOME') }}/.poetry/bin"
          warn: false
      - name: Add Poetry to .bash_profile
        lineinfile: 
          backup: true
          create: true
          line: export PATH="$HOME/.poetry/bin:$PATH"
          path: "{{ lookup('env','HOME') }}/.bash_profile"
          state: present
      - name: Add Poetry to bash_completion
        shell: |
          "source {{ lookup('env','HOME') }}/.poetry/env"
          poetry completions bash > /etc/bash_completion.d/poetry.bash-completion
        args:
          creates: /etc/bash_completion.d/poetry.bash-completion
          warn: false
